from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker
from models import Base
from config import DATABASE_URL
import hashlib

engine = create_async_engine(DATABASE_URL, echo=False)
async_session = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)


async def init_db():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    from models import User, Book
    from sqlalchemy import select

    async with async_session() as session:
        # Check if admin exists
        result = await session.execute(select(User).where(User.email == "admin@school.ru"))
        admin = result.scalar_one_or_none()
        if not admin:
            admin = User(
                name="Администратор",
                email="admin@school.ru",
                password_hash=hashlib.sha256("admin123".encode()).hexdigest(),
                role="admin",
                is_active=True
            )
            session.add(admin)

        # Check if books exist
        result = await session.execute(select(Book).limit(1))
        if not result.scalar_one_or_none():
            sample_books = [
                # === УЧЕБНИКИ (5-11 классы) ===
                Book(title="Алгебра 7-9 класс", author="Макарычев Ю.Н.", year=2023, grade="7-9", purpose="учебник", total_copies=30, available_copies=30, cover_url=None,
                    description="Базовый учебник алгебры для 7-9 классов. Содержит все разделы: одночлены и многочлены, квадратные уравнения, функции и графики, прогрессии. Соответствует ФГОС."),
                Book(title="Алгебра 10-11 класс", author="Колмогоров А.Н.", year=2023, grade="10-11", purpose="учебник", total_copies=20, available_copies=20, cover_url=None,
                    description="Углублённый курс алгебры для старших классов. Включает тригонометрические функции, производную, интегралы, показательные и логарифмические уравнения."),
                Book(title="Геометрия 7-9 класс", author="Атанасян Л.С.", year=2023, grade="7-9", purpose="учебник", total_copies=25, available_copies=25, cover_url=None,
                    description="Классический учебник геометрии. Планиметрия от начальных понятий до теорем синусов и косинусов. Много практических задач с чертежами."),
                Book(title="Геометрия 10-11 класс", author="Атанасян Л.С.", year=2023, grade="10-11", purpose="учебник", total_copies=18, available_copies=18, cover_url=None,
                    description="Стереометрия для старших классов. Взаимное расположение прямых и плоскостей в пространстве, многогранники, тела вращения, объёмы."),
                Book(title="Русский язык 5-6 класс", author="Баранов М.Т.", year=2022, grade="5-6", purpose="учебник", total_copies=25, available_copies=25, cover_url=None,
                    description="Начальный систематический курс русского языка: фонетика, лексика, морфология, орфография. Правила, упражнения, словарная работа."),
                Book(title="Русский язык 7-8 класс", author="Баранов М.Т.", year=2022, grade="7-8", purpose="учебник", total_copies=22, available_copies=22, cover_url=None,
                    description="Продолжение курса русского языка: причастие, деепричастие, наречие, служебные части речи, синтаксис простого предложения."),
                Book(title="Литература 5 класс", author="Коровина В.Я.", year=2023, grade="5", purpose="учебник", total_copies=20, available_copies=20, cover_url=None,
                    description="Введение в мир литературы. Русские народные сказки, басни Крылова, стихи Пушкина и Лермонтова, рассказы Чехова и Паустовского."),
                Book(title="Литература 6 класс", author="Коровина В.Я.", year=2023, grade="6", purpose="учебник", total_copies=20, available_copies=20, cover_url=None,
                    description="Произведения устного народного творчества, древнерусская литература. Стихи и проза XIX века, зарубежная литература для детей."),
                Book(title="Литература 7 класс", author="Коровина В.Я.", year=2023, grade="7", purpose="учебник", total_copies=18, available_copies=18, cover_url=None,
                    description="Былины, поэмы Пушкина и Лермонтова, «Тарас Бульба» Гоголя, рассказы Тургенева, стихи Некрасова и Маяковского."),
                Book(title="Литература 8 класс", author="Коровина В.Я.", year=2023, grade="8", purpose="учебник", total_copies=20, available_copies=20, cover_url=None,
                    description="«Капитанская дочка» Пушкина, «Ревизор» Гоголя, «После бала» Толстого. Анализ композиции, образов, художественных средств."),
                Book(title="Литература 9 класс", author="Коровина В.Я.", year=2023, grade="9", purpose="учебник", total_copies=18, available_copies=18, cover_url=None,
                    description="«Слово о полку Игореве», «Евгений Онегин» и «Герой нашего времени» — ключевые произведения для подготовки к ОГЭ по литературе."),
                Book(title="Физика 7-8 класс", author="Пёрышкин А.В.", year=2023, grade="7-8", purpose="учебник", total_copies=20, available_copies=20, cover_url=None,
                    description="Основы физики: строение вещества, механическое движение, давление, сила Архимеда, тепловые явления, агрегатные состояния."),
                Book(title="Физика 9 класс", author="Пёрышкин А.В.", year=2023, grade="9", purpose="учебник", total_copies=20, available_copies=20, cover_url=None,
                    description="Кинематика и динамика, законы Ньютона, импульс, работа и энергия, механические колебания и волны, звук."),
                Book(title="Физика 10-11 класс", author="Мякишев Г.Я.", year=2023, grade="10-11", purpose="учебник", total_copies=15, available_copies=15, cover_url=None,
                    description="Молекулярная физика, термодинамика, электродинамика, магнитное поле, оптика, квантовая физика. Подготовка к ЕГЭ."),
                Book(title="Химия 8-9 класс", author="Габриелян О.С.", year=2022, grade="8-9", purpose="учебник", total_copies=15, available_copies=15, cover_url=None,
                    description="Начальный курс химии: атомы и молекулы, химические реакции, растворы, окислительно-восстановительные реакции, металлы и неметаллы."),
                Book(title="Химия 10-11 класс", author="Габриелян О.С.", year=2022, grade="10-11", purpose="учебник", total_copies=12, available_copies=12, cover_url=None,
                    description="Органическая химия: углеводороды, спирты, альдегиды, кислоты, жиры, углеводы, белки. Химия и жизнь."),
                Book(title="История России 6 класс", author="Торкунов А.В.", year=2023, grade="6", purpose="учебник", total_copies=20, available_copies=20, cover_url=None,
                    description="Древняя Русь от славянских племён до монгольского нашествия. Первые князья, Крещение Руси, культура и быт."),
                Book(title="История России 7 класс", author="Торкунов А.В.", year=2023, grade="7", purpose="учебник", total_copies=18, available_copies=18, cover_url=None,
                    description="Россия в XVI-XVII веках: Иван Грозный, Смутное время, первые Романовы, церковный раскол, освоение Сибири."),
                Book(title="История России 8 класс", author="Торкунов А.В.", year=2023, grade="8", purpose="учебник", total_copies=18, available_copies=18, cover_url=None,
                    description="Россия в XVIII веке: реформы Петра I, дворцовые перевороты, правление Екатерины II, крестьянская война Пугачёва."),
                Book(title="Всеобщая история 9 класс", author="Сороко-Цюпа О.С.", year=2023, grade="9", purpose="учебник", total_copies=15, available_copies=15, cover_url=None,
                    description="История Нового времени: Великая французская революция, наполеоновские войны, объединение Италии и Германии, Первая мировая."),
                Book(title="География 5-6 класс", author="Алексеев А.И.", year=2023, grade="5-6", purpose="учебник", total_copies=20, available_copies=20, cover_url=None,
                    description="Начальный курс географии: планета Земля, литосфера, гидросфера, атмосфера, биосфера. Географические открытия и карты."),
                Book(title="География 7 класс", author="Коринская В.А.", year=2023, grade="7", purpose="учебник", total_copies=18, available_copies=18, cover_url=None,
                    description="Материки и океаны: Африка, Австралия, Антарктида, Южная и Северная Америка, Евразия. Природные зоны и население."),
                Book(title="Биология 5-6 класс", author="Пасечник В.В.", year=2023, grade="5-6", purpose="учебник", total_copies=18, available_copies=18, cover_url=None,
                    description="Биология как наука: клетка, ткани, органы. Царства растений, бактерий и грибов. Фотосинтез, размножение, развитие."),
                Book(title="Биология 7-8 класс", author="Пасечник В.В.", year=2023, grade="7-8", purpose="учебник", total_copies=16, available_copies=16, cover_url=None,
                    description="Зоология и анатомия: беспозвоночные и позвоночные животные. Организм человека, кровеносная, нервная и пищеварительная системы."),
                Book(title="Биология 9 класс", author="Пасечник В.В.", year=2023, grade="9", purpose="учебник", total_copies=15, available_copies=15, cover_url=None,
                    description="Общая биология: генетика, эволюция, экология, происхождение человека. Подготовка к ОГЭ по биологии."),
                Book(title="Информатика 7-9 класс", author="Босова Л.Л.", year=2023, grade="7-9", purpose="учебник", total_copies=25, available_copies=25, cover_url=None,
                    description="Основы информатики: компьютер как устройство, программирование на Python, алгоритмы, базы данных, интернет-технологии."),
                Book(title="Информатика 10-11 класс", author="Босова Л.Л.", year=2023, grade="10-11", purpose="учебник", total_copies=15, available_copies=15, cover_url=None,
                    description="Углублённая информатика: структуры данных, объектно-ориентированное программирование, моделирование, информационная безопасность."),
                Book(title="Обществознание 6-7 класс", author="Боголюбов Л.Н.", year=2023, grade="6-7", purpose="учебник", total_copies=20, available_copies=20, cover_url=None,
                    description="Человек в обществе: личность, семья, школа, труд, Родина. Основы социальных норм и правил поведения."),
                Book(title="Обществознание 8-9 класс", author="Боголюбов Л.Н.", year=2023, grade="8-9", purpose="учебник", total_copies=18, available_copies=18, cover_url=None,
                    description="Общество и государство: экономика, политика, право, культура. Конституция РФ, права и обязанности граждан."),
                Book(title="Английский язык 5 класс", author="Ваулина Ю.Е.", year=2023, grade="5", purpose="учебник", total_copies=30, available_copies=30, cover_url=None,
                    description="Spotlight 5: начальный курс английского. Лексика по темам «Школа», «Семья», «Дом», «Животные». Грамматика настоящего времени."),
                Book(title="Английский язык 6 класс", author="Ваулина Ю.Е.", year=2023, grade="6", purpose="учебник", total_copies=28, available_copies=28, cover_url=None,
                    description="Spotlight 6: расширение словарного запаса. Времена глаголов, степени сравнения прилагательных, модальные глаголы."),
                Book(title="Английский язык 7-8 класс", author="Ваулина Ю.Е.", year=2023, grade="7-8", purpose="учебник", total_copies=25, available_copies=25, cover_url=None,
                    description="Spotlight 7-8: подготовка к ОГЭ. Пассивный залог, условные предложения, косвенная речь, чтение аутентичных текстов."),
                Book(title="Математика 5-6 класс", author="Виленкин Н.Я.", year=2022, grade="5-6", purpose="учебник", total_copies=30, available_copies=30, cover_url=None,
                    description="Начальный курс математики: натуральные числа, дроби, проценты, пропорции, основы геометрии. Развитие вычислительных навыков."),
                Book(title="ОБЖ 8-9 класс", author="Смирнов А.Т.", year=2023, grade="8-9", purpose="учебник", total_copies=15, available_copies=15, cover_url=None,
                    description="Основы безопасности жизнедеятельности: личная безопасности, пожарная безопасность, правила дорожного движения, оказание первой помощи, здоровый образ жизни."),
                Book(title="Физическая культура 5-7 класс", author="Виленский М.Я.", year=2023, grade="5-7", purpose="учебник", total_copies=20, available_copies=20, cover_url=None,
                    description="Теория и практика физической культуры: гимнастика, лёгкая атлетика, спортивные игры, лыжная подготовка, режим дня и закаливание."),
                Book(title="Музыка 5-7 класс", author="Сергеева Г.П.", year=2023, grade="5-7", purpose="учебник", total_copies=15, available_copies=15, cover_url=None,
                    description="Мир музыкального искусства: жанры и формы музыки, композиторы XIX-XX веков, народная музыка, современные музыкальные направления."),
                Book(title="Изобразительное искусство 5-7 класс", author="Неменская Л.А.", year=2023, grade="5-7", purpose="учебник", total_copies=15, available_copies=15, cover_url=None,
                    description="Основы изобразительного искусства: рисунок, живопись, композиция. Знакомство с творчеством великих художников и архитектурой."),
                Book(title="Технология 5-7 класс", author="Казакевич В.М.", year=2023, grade="5-7", purpose="учебник", total_copies=20, available_copies=20, cover_url=None,
                    description="Трудовое обучение и техническое творчество: работа с деревом, металлом, тканью. Основы проектной деятельности и моделирования."),
                Book(title="Право 10-11 класс", author="Боголюбов Л.Н.", year=2023, grade="10-11", purpose="учебник", total_copies=10, available_copies=10, cover_url=None,
                    description="Основы правоведения: теория государства и права, отраслевые системы права, правоохранительные органы, международное гуманитарное право."),
                Book(title="Экономика 10-11 класс", author="Липсиц И.В.", year=2023, grade="10-11", purpose="учебник", total_copies=10, available_copies=10, cover_url=None,
                    description="Введение в экономику: рыночный механизм, спрос и предложение, фирмы и конкуренция, роль государства в экономике, налоги и бюджет."),

                # === РУССКАЯ КЛАССИКА ===
                Book(title="Война и мир (том 1-4)", author="Толстой Л.Н.", year=1869, grade="10", purpose="внеклассное чтение", total_copies=10, available_copies=10, cover_url=None,
                    description="Величайший роман-эпопея мировой литературы. Эпоха наполеоновских войн, судьбы дворянских семей, искания Пьера Безухова и Андрея Болконского, диалектика души."),
                Book(title="Анна Каренина", author="Толстой Л.Н.", year=1877, grade="10", purpose="внеклассное чтение", total_copies=8, available_copies=8, cover_url=None,
                    description="Трагическая история любви замужней женщины из высшего света. Семья, брак и нравственность в русском обществе XIX века. «Все счастливые семьи похожи друг на друга...»"),
                Book(title="Преступление и наказание", author="Достоевский Ф.М.", year=1866, grade="10-11", purpose="внеклассное чтение", total_copies=8, available_copies=8, cover_url=None,
                    description="Философско-психологический роман о студенте Раскольникове, решившемся на убийство из теории о «сверхчеловеке». Мучительное раскаяние и путь к искуплению через страдание."),
                Book(title="Идиот", author="Достоевский Ф.М.", year=1869, grade="10-11", purpose="внеклассное чтение", total_copies=6, available_copies=6, cover_url=None,
                    description="Роман о «положительно прекрасном человеке» — князе Мышкине, чья доброта и наивность сталкиваются с жестоким и корыстным миром петербургского общества."),
                Book(title="Братья Карамазовы", author="Достоевский Ф.М.", year=1880, grade="11", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="Последний и самый сложный роман Достоевского. История семьи Карамазовых: отцеубийство, вера и безверие, поединок дьявола и Бога в душе человека."),
                Book(title="Мастер и Маргарита", author="Булгаков М.А.", year=1966, grade="11", purpose="внеклассное чтение", total_copies=7, available_copies=7, cover_url=None,
                    description="Гениальный роман-мистификация. Сатана с его свитой посещает Москву 1930-х. История любви Мастера и Маргариты, древний сюжет о Понтии Пилате и Иешуа."),
                Book(title="Собачье сердце", author="Булгаков М.А.", year=1925, grade="9", purpose="внеклассное чтение", total_copies=6, available_copies=6, cover_url=None,
                    description="Острая сатирическая повесть. Профессор Преображенский превращает дворового пса Шарика в человека — и получает чудовищный результат, пародию на советского обывателя."),
                Book(title="Белая гвардия", author="Булгаков М.А.", year=1925, grade="11", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="Роман о Гражданской войне на Украине. Семья Турбиных в охваченном хаосом Киеве 1918 года. Долг, честь и гибель старого мира."),
                Book(title="Евгений Онегин", author="Пушкин А.С.", year=1833, grade="9", purpose="внеклассное чтение", total_copies=12, available_copies=12, cover_url=None,
                    description="«Энциклопедия русской жизни» в стихах. История разочарованного аристократа Онегина и искренней Татьяны Лариной. Любовь, дружба, дуэль — вечные темы русской литературы."),
                Book(title="Капитанская дочка", author="Пушкин А.С.", year=1836, grade="8", purpose="внеклассное чтение", total_copies=10, available_copies=10, cover_url=None,
                    description="Исторический роман о Пугачёвском бунте. Юный офицер Пётр Гринёв оказывается в эпицентре событий, где решающую роль играют честь, верность и любовь к Маше Мироновой."),
                Book(title="Повести Белкина", author="Пушкин А.С.", year=1831, grade="7", purpose="внеклассное чтение", total_copies=8, available_copies=8, cover_url=None,
                    description="Сборник из пяти повестей: «Станционный смотритель», «Метель», «Выстрел», «Барышня-крестьянка», «Гробовщик». Основоположник русского реалистического рассказа."),
                Book(title="Герой нашего времени", author="Лермонтов М.Ю.", year=1840, grade="9", purpose="внеклассное чтение", total_copies=10, available_copies=10, cover_url=None,
                    description="Первый психологический роман в русской литературе. Разочарованный Печорин, «лишний человек», в поисках смысла жизни на фоне романтического Кавказа."),
                Book(title="Мёртвые души", author="Гоголь Н.В.", year=1842, grade="9", purpose="внеклассное чтение", total_copies=10, available_copies=10, cover_url=None,
                    description="Поэма в прозе. Авантюрист Чичиков скупает «мёртвые души» крестьян. Галерея помещиков-сатирических типов: Манилов, Коробочка, Ноздрёв, Плюшкин, Собакевич."),
                Book(title="Ревизор", author="Гоголь Н.В.", year=1836, grade="8", purpose="внеклассное чтение", total_copies=8, available_copies=8, cover_url=None,
                    description="Бессмертная комедия нравов. Уездные чиновники принимают мелкого петербургского чиновника за ревизора. «На зеркало неча пенять, коли рожа крива»."),
                Book(title="Тарас Бульба", author="Гоголь Н.В.", year=1835, grade="7", purpose="внеклассное чтение", total_copies=8, available_copies=8, cover_url=None,
                    description="Героическая повесть о запорожских казаках. Старый полковник Тарас Бульба воспитывает сыновей в духе воинской доблести. Трагедия предательства и отцовской мести."),
                Book(title="Отцы и дети", author="Тургенев И.С.", year=1862, grade="10", purpose="внеклассное чтение", total_copies=8, available_copies=8, cover_url=None,
                    description="Роман о вечном конфликте поколений. Нигилист Базаров отрицает любовь, искусство и авторитеты — но жизнь заставляет его пересмотреть свои убеждения."),
                Book(title="Гроза", author="Островский А.Н.", year=1859, grade="10", purpose="внеклассное чтение", total_copies=7, available_copies=7, cover_url=None,
                    description="Драма о «тёмном царстве» купеческого быта. Катерина — чистая душа, задыхающаяся от тирании свекрови и слабости мужа. Любовь как грех и единственный выход."),
                Book(title="Обломов", author="Гончаров И.А.", year=1859, grade="10", purpose="внеклассное чтение", total_copies=7, available_copies=7, cover_url=None,
                    description="Роман об «обломовщине» — русской лени и апатии. Добрый, умный, но безвольный барин Илья Обломов не может встать с дивана, предпочитая сны реальности."),
                Book(title="Тихий Дон", author="Шолохов М.А.", year=1940, grade="11", purpose="внеклассное чтение", total_copies=6, available_copies=6, cover_url=None,
                    description="Роман-эпопея о жизни донского казачества в эпоху Первой мировой и Гражданской войны. Трагическая судьба Григория Мелехова между двумя правдами."),
                Book(title="Судьба человека", author="Шолохов М.А.", year=1957, grade="9", purpose="внеклассное чтение", total_copies=8, available_copies=8, cover_url=None,
                    description="Рассказ о русском солдате Андрее Соколове, прошедшем ад фашистского плена, потерявшем всю семью, но сохранившем человечность и способность любить."),
                Book(title="Дама с собачкой", author="Чехов А.П.", year=1899, grade="8", purpose="внеклассное чтение", total_copies=6, available_copies=6, cover_url=None,
                    description="Шедевр чеховской прозы. Курортный роман между скучающим московским банкиром и молодой замужней женщиной перерастает в настоящее глубокое чувство."),
                Book(title="Вишнёвый сад", author="Чехов А.П.", year=1904, grade="10", purpose="внеклассное чтение", total_copies=7, available_copies=7, cover_url=None,
                    description="Последняя пьеса Чехова. Усадьба с вишнёвым садом продаётся за долги. Прощание старого мира дворянства с наступлением новой эпохи купцов и дельцов."),
                Book(title="На дне", author="Горький М.", year=1902, grade="11", purpose="внеклассное чтение", total_copies=6, available_copies=6, cover_url=None,
                    description="Социально-философская драма. Обитатели ночлежки — люди, опустившиеся на «дно» жизни. Спор о правде и лжи, о том, что спасает человека: надежда или горькая правда."),
                Book(title="Старуха Изергиль", author="Горький М.", year=1895, grade="11", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="Романтический рассказ с легендами о Ларре и Данко. Пламенное сердце Данко, вырванное из груди, чтобы осветить путь людям — символ самопожертвования."),
                Book(title="Олеся", author="Куприн А.И.", year=1898, grade="9", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="Поэтическая повесть о любви городского барина и «ведьмы» Олеси из полесского леса. Магия, природа и трагическое столкновение с деревенским невежеством."),
                Book(title="Гранатовый браслет", author="Куприн А.И.", year=1911, grade="10", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="Повесть о безответной любви. Скромный чиновник Желтков на протяжении восьми лет безнадёжно влюблён в княгиню. Его единственный подарок — гранатовый браслет."),
                Book(title="Господин из Сан-Франциско", author="Бунин И.А.", year=1915, grade="11", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="Философский рассказ о тщете богатства. Американский миллионер умирает на курорте, и его тело возвращают домой в багажном отсеке корабля, как ненужную вещь."),
                Book(title="Тёмные аллеи", author="Бунин И.А.", year=1943, grade="11", purpose="внеклассное чтение", total_copies=4, available_copies=4, cover_url=None,
                    description="Цикл рассказов о любви во всех её проявлениях. «Тёмные аллеи» — самые пронзительные истории о страсти, разлуке, воспоминаниях и непрошедшем чувстве."),
                Book(title="Пиковая дама", author="Пушкин А.С.", year=1834, grade="8", purpose="внеклассное чтение", total_copies=6, available_copies=6, cover_url=None,
                    description="Мистическая повесть о карточной игре. Инженер Германн жаждет узнать тайну трёх карт графини — и эта одержимость приводит его к безумию."),
                Book(title="Недоросль", author="Фонвизин Д.И.", year=1782, grade="8", purpose="внеклассное чтение", total_copies=6, available_copies=6, cover_url=None,
                    description="Сатирическая комедия XVIII века. Митрофанушка — ленивый и невежественный «недоросль», который не хочет учиться. «Не хочу учиться, хочу жениться!»"),
                Book(title="Горе от ума", author="Грибоедов А.С.", year=1825, grade="9", purpose="внеклассное чтение", total_copies=7, available_copies=7, cover_url=None,
                    description="Комедия в стихах, разобранная на цитаты. Умный и свободомыслящий Чацкий возвращается в Москву и сталкивается с косным фамусовским обществом."),
                Book(title="Бедная Лиза", author="Карамзин Н.М.", year=1792, grade="8", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="Сентиментальная повесть, покорившая Россию. Крестьянка Лиза полюбила дворянина Эраста, но её чистое чувство разбивается о сословные предрассудки."),
                Book(title="Кому на Руси жить хорошо", author="Некрасов Н.А.", year=1874, grade="10", purpose="внеклассное чтение", total_copies=6, available_copies=6, cover_url=None,
                    description="Поэма-эпопея о поисках счастливого человека на Руси. Семь крестьян путешествуют по стране и понимают, что счастье не в деньгах, а в народной душе."),
                Book(title="Слово о полку Игореве", author="Неизвестный", year=1185, grade="9", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="Величайший памятник древнерусской литературы. Повесть о неудачном походе князя Игоря на половцев, призыв к единению русских земель перед лицом врага."),

                # === ЗАРУБЕЖНАЯ ЛИТЕРАТУРА ===
                Book(title="Ромео и Джульетта", author="Шекспир У.", year=1597, grade="8", purpose="внеклассное чтение", total_copies=8, available_copies=8, cover_url=None,
                    description="Бессмертная трагедия о любви юноши и девушки из враждующих семей. История Ромео и Джульетты стала символом самой прекрасной и трагической любви."),
                Book(title="Гамлет", author="Шекспир У.", year=1601, grade="9", purpose="внеклассное чтение", total_copies=7, available_copies=7, cover_url=None,
                    description="Величайшая пьеса мировой драматургии. «Быть или не быть?» — датский принц размышляет о жизни, смерти, мести и нравственном выборе."),
                Book(title="Фауст", author="Гёте И.В.", year=1808, grade="9", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="Философская трагедия о докторе Фаусте, продавшем душу Мефистофелю в обмен на знание, наслаждение и власть. Символ вечного поиска истины."),
                Book(title="Собор Парижской Богоматери", author="Гюго В.", year=1831, grade="8", purpose="внеклассное чтение", total_copies=6, available_copies=6, cover_url=None,
                    description="Исторический роман о средневековом Париже. Судьбы горбуна Квазимодо, цыганки Эсмеральды и священника Фролло переплетены у стен великого собора."),
                Book(title="Три мушкетёра", author="Дюма А.", year=1844, grade="7", purpose="внеклассное чтение", total_copies=8, available_copies=8, cover_url=None,
                    description="Приключенческий роман о юном д'Артаньяне и его друзьях. «Один за всех и все за одного!» — девиз мушкетёров, защищающих честь королевы и Франции."),
                Book(title="Приключения Шерлока Холмса", author="Дойл А.К.", year=1892, grade="7", purpose="внеклассное чтение", total_copies=8, available_copies=8, cover_url=None,
                    description="Сборник рассказов о величайшем сыщике всех времён. Дедуктивный метод, курение трубки, игра на скрипке и помощь верного доктора Ватсона."),
                Book(title="Декамерон", author="Боккаччо Дж.", year=1353, grade="11", purpose="внеклассное чтение", total_copies=4, available_copies=4, cover_url=None,
                    description="Сто новелл, рассказанных молодыми людьми во время чумы. Остроумные, фривольные и поучительные истории о любви, судьбе и человеческой глупости."),
                Book(title="Гордость и предубеждение", author="Остен Дж.", year=1813, grade="9", purpose="внеклассное чтение", total_copies=6, available_copies=6, cover_url=None,
                    description="Шедевр английской литературы. Умная и острая на язык Элизабет Беннет встречает загадочного мистера Дарси, и между ними вспыхивает искра."),
                Book(title="Портрет Дориана Грея", author="Уайльд О.", year=1890, grade="10", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="Мистический роман о красоте и пороке. Юный Дориан остаётся вечно молодым, в то время как его портрет стареет и впитывает все его грехи."),
                Book(title="Божественная комедия", author="Данте А.", year=1321, grade="11", purpose="внеклассное чтение", total_copies=4, available_copies=4, cover_url=None,
                    description="Эпическая поэма о путешествии души через Ад, Чистилище и Рай. Данте ведёт Вергилий, а его проводница Беатриче — символ божественной любви."),
                Book(title="Дон Кихот", author="Сервантес М.", year=1615, grade="8", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="Величайший роман испанской литературы. Благородный идальго, начитавшись рыцарских романов, отправляется с верным Санчо Пансой совершать подвиги."),
                Book(title="Путешествия Гулливера", author="Свифт Дж.", year=1726, grade="7", purpose="внеклассное чтение", total_copies=6, available_copies=6, cover_url=None,
                    description="Сатирический роман о приключениях Гулливера в фантастических странах: лилипутов, великанов, летающем острове и разумных лошадях."),
                Book(title="Двадцать тысяч лье под водой", author="Верн Ж.", year=1870, grade="6", purpose="внеклассное чтение", total_copies=7, available_copies=7, cover_url=None,
                    description="Знаменитый научно-фантастический роман. Профессор Аронакс и капитан Немо на подводной лодке «Наутилус» исследуют таинственный подводный мир."),
                Book(title="Всадник без головы", author="Рид М.", year=1865, grade="7", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="Приключенческий роман о Диком Западе. В прериях Техаса появляется таинственный всадник без головы — и это связано с исчезновением молодого плантатора."),

                # === СОВРЕМЕННАЯ ЛИТЕРАТУРА ===
                Book(title="451° по Фаренгейту", author="Брэдбери Р.", year=1953, grade="10", purpose="внеклассное чтение", total_copies=6, available_copies=6, cover_url=None,
                    description="Роман-антиутопия о будущем, где книги запрещены, а пожарные сжигают их. Пожарный Монтэг начинает сомневаться в правильности системы."),
                Book(title="Маленький принц", author="Сент-Экзюпери А.", year=1943, grade="6", purpose="внеклассное чтение", total_copies=10, available_copies=10, cover_url=None,
                    description="Философская сказка для детей и взрослых. Маленький принц путешествует по планетам и открывает простые истины: «Мы в ответе за тех, кого приручили»."),
                Book(title="1984", author="Оруэлл Дж.", year=1949, grade="11", purpose="внеклассное чтение", total_copies=6, available_copies=6, cover_url=None,
                    description="Культовая антиутопия. Тоталитарное государство Океания, «Большой Брат следит за тобой», двоемыслие и любовь как последнее проявление свободы."),
                Book(title="Скотный двор", author="Оруэлл Дж.", year=1945, grade="10", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="Сатирическая притча о революции. Животные изгоняют людей с фермы и пытаются построить равенство — но «все животные равны, хотя некоторые равнее»."),
                Book(title="Убить пересмешника", author="Ли Х.", year=1960, grade="9", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="Роман о расовой несправедливости на американском Юге глазами девочки Скаут. Её отец, адвокат Аттикус Финч, защищает несправедливо обвинённого чернокожего."),
                Book(title="Над пропастью во ржи", author="Сэлинджер Дж.Д.", year=1951, grade="10", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="Роман-исповедь подростка Холдена Колфилда. Мятеж против «фальшивого» мира взрослых, одиночество и желание спасать детей над пропастью во ржи."),
                Book(title="Старик и море", author="Хемингуэй Э.", year=1952, grade="8", purpose="внеклассное чтение", total_copies=6, available_copies=6, cover_url=None,
                    description="Повесть-притча о старом рыбаке Сантьяго. Его схватка с огромной рыбой в открытом море — символ мужества, стойкости и достоинства человека."),
                Book(title="Цветы для Элджернона", author="Киз Д.", year=1959, grade="9", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="Научно-фантастический роман в форме дневника. Умственно отсталый Чарли становится гением после эксперимента — но улучшение оказывается временным."),
                Book(title="Повелитель мух", author="Голдинг У.", year=1954, grade="10", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="Аллегорический роман о тёмной стороне человеческой натуры. Группа мальчиков на необитаемом острове пытается построить цивилизацию, но скатывается в варварство."),
                Book(title="Сто лет одиночества", author="Маркес Г.", year=1967, grade="11", purpose="внеклассное чтение", total_copies=4, available_copies=4, cover_url=None,
                    description="Шедевр магического реализма. История семьи Буэндия и города Макондо на протяжении ста лет. Любовь, война, прогресс и неизбежный распад."),
                Book(title="Три товарища", author="Ремарк Э.М.", year=1936, grade="10", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="Роман о дружбе трёх фронтовых товарищей в Веймарской Германии. Любовь Робби к смертельно больной Пат на фоне кризиса и безвременья."),
                Book(title="Великий Гэтсби", author="Фицджеральд Ф.", year=1925, grade="10", purpose="внеклассное чтение", total_copies=5, available_copies=5, cover_url=None,
                    description="«Век джаза» в Америке. Таинственный миллионер Гэтсби даёт роскошные вечеринки ради одной цели — вернуть любовь своей жизни, прекрасную Дэйзи."),
                Book(title="Зеленая миля", author="Кинг С.", year=1996, grade="11", purpose="внеклассное чтение", total_copies=4, available_copies=4, cover_url=None,
                    description="Мистическая драма о смертной казни. Гигантский заключённый Джон Коффи обладает даром исцеления — но его ждёт «зелёная миля» к электрическому стулу."),
                Book(title="Хоббит", author="Толкин Дж.Р.Р.", year=1937, grade="6", purpose="внеклассное чтение", total_copies=6, available_copies=6, cover_url=None,
                    description="Сказочная повесть о путешествии скромного хоббита Бильбо Бэггинса. Дракон Смауг, кольцо всевластья, гномы и эльфы — начало легендариума Средиземья."),
                Book(title="Гарри Поттер и философский камень", author="Роулинг Дж.К.", year=1997, grade="5", purpose="внеклассное чтение", total_copies=8, available_copies=8, cover_url=None,
                    description="Первая книга о мальчике, который выжил. Гарри Поттер поступает в Хогвартс, находит друзей и врагов и раскрывает тайну философского камня."),
                Book(title="Метро 2033", author="Глуховский Д.А.", year=2005, grade="11", purpose="внеклассное чтение", total_copies=4, available_copies=4, cover_url=None,
                    description="Постапокалиптический роман о выживании человечества в московском метро после ядерной войны. Станции-государства, мутанты и борьба за будущее."),
                Book(title="Ночной дозор", author="Лукьяненко С.В.", year=1998, grade="10", purpose="внеклассное чтение", total_copies=4, available_copies=4, cover_url=None,
                    description="Первая книга цикла «Дозоры». В Москве действуют Иные — маги и вампиры, разделённые на Светлых и Тёмных. Ночной Дозор следит за соблюдением равновесия."),
                Book(title="Чувство и чувствительность", author="Остен Дж.", year=1811, grade="9", purpose="внеклассное чтение", total_copies=4, available_copies=4, cover_url=None,
                    description="Роман о двух сёстрах — рассудительной Элинор и импульсивной Марианне. Испытания любовью, денежные трудности и торжество здравого смысла."),
                Book(title="Таинственный сад", author="Бёрнетт Ф.", year=1911, grade="5", purpose="внеклассное чтение", total_copies=6, available_copies=6, cover_url=None,
                    description="Добрая повесть о силе дружбы и природы. Сирота Мэри Леннокс находит заброшенный сад в поместье своего дяди и вместе с кузеном возвращает его к жизни."),
                Book(title="Приключения Тома Сойера", author="Твен М.", year=1876, grade="6", purpose="внеклассное чтение", total_copies=8, available_copies=8, cover_url=None,
                    description="Классика американской литературы. Непоседливый Том Сойер находит приключения в маленьком городке на Миссисипи: поиск сокровищ, пещера и спасение невиновного."),
            ]
            for book in sample_books:
                session.add(book)

        await session.commit()


async def get_session():
    async with async_session() as session:
        yield session